import { GiftSuggestion, Product, Store } from '@/types';

// ============================================================
// MOCK AI GIFT SUGGESTIONS
// Realistic Vietnamese gift suggestions by occasion
// ============================================================

export const MOCK_SUGGESTIONS_BY_OCCASION: Record<string, GiftSuggestion[]> = {
  birthday: [
    {
      id: '1',
      productName: 'Bình giữ nhiệt khắc tên cá nhân hóa',
      reason: 'Người Bảo Bình như bạn ấy thường yêu thích những món đồ độc đáo và có ý nghĩa. Bình giữ nhiệt khắc tên vừa thực tế vừa khiến người nhận cảm thấy đặc biệt mỗi ngày.',
      estimatedPriceRange: '150.000đ - 280.000đ',
      searchKeyword: 'bình giữ nhiệt khắc tên',
      emoji: '🫖',
      category: 'Đồ dùng cá nhân',
    },
    {
      id: '2',
      productName: 'Set chăm sóc da mini luxury',
      reason: 'Với tính cách yêu làm đẹp, một bộ skincare cao cấp mini sẽ giúp bạn ấy cảm thấy được chiều chuộng và thư giãn sau những ngày bận rộn.',
      estimatedPriceRange: '200.000đ - 350.000đ',
      searchKeyword: 'set skincare mini gift',
      emoji: '✨',
      category: 'Làm đẹp',
    },
    {
      id: '3',
      productName: 'Lắc tay bạc 925 mặt đá tự nhiên',
      reason: 'Đồ trang sức tinh tế luôn là lựa chọn an toàn và ý nghĩa cho sinh nhật. Đá tự nhiên phù hợp với cung hoàng đạo sẽ tạo thêm câu chuyện đặc biệt.',
      estimatedPriceRange: '280.000đ - 450.000đ',
      searchKeyword: 'lắc tay bạc 925 đá tự nhiên',
      emoji: '💎',
      category: 'Trang sức',
    },
    {
      id: '4',
      productName: 'Sách "Atomic Habits" bìa cứng',
      reason: 'Cho người yêu thích đọc sách và muốn phát triển bản thân, đây là cuốn sách được hàng triệu người yêu thích — vừa truyền cảm hứng vừa thiết thực.',
      estimatedPriceRange: '120.000đ - 180.000đ',
      searchKeyword: 'sách atomic habits bìa cứng',
      emoji: '📚',
      category: 'Sách',
    },
    {
      id: '5',
      productName: 'Đèn LED trang trí phòng aesthetic',
      reason: 'Với sở thích sáng tạo và yêu không gian đẹp, bộ đèn LED tạo bầu không khí ấm cúng sẽ biến phòng ngủ của bạn ấy thành một góc riêng thật "vibe".',
      estimatedPriceRange: '80.000đ - 150.000đ',
      searchKeyword: 'đèn LED phòng ngủ aesthetic',
      emoji: '💡',
      category: 'Trang trí',
    },
    {
      id: '6',
      productName: 'Túi tote canvas in hình cá nhân hóa',
      reason: 'Thực tế mà không kém phần phong cách — túi tote vừa để đi học, đi chơi, vừa là món quà thể hiện sự cẩn thận trong việc chọn lựa của bạn.',
      estimatedPriceRange: '90.000đ - 180.000đ',
      searchKeyword: 'túi tote canvas in hình',
      emoji: '🛍️',
      category: 'Thời trang',
    },
  ],
  valentine: [
    {
      id: '1',
      productName: 'Gấu bông custom in ảnh couple',
      reason: 'Gấu bông in ảnh hai người là món quà lãng mạn và độc đáo — mỗi lần nhìn thấy, bạn ấy sẽ nhớ đến khoảnh khắc đẹp của hai người.',
      estimatedPriceRange: '200.000đ - 380.000đ',
      searchKeyword: 'gấu bông in ảnh custom',
      emoji: '🧸',
      category: 'Quà lãng mạn',
    },
    {
      id: '2',
      productName: 'Hộp socola handmade cao cấp',
      reason: 'Socola là ngôn ngữ tình yêu không bao giờ lỗi thời. Hộp handmade với thiết kế sang trọng sẽ khiến Valentine năm nay thêm ngọt ngào.',
      estimatedPriceRange: '150.000đ - 300.000đ',
      searchKeyword: 'socola handmade hộp quà valentine',
      emoji: '🍫',
      category: 'Thực phẩm',
    },
    {
      id: '3',
      productName: 'Nến thơm hoa khô decor',
      reason: 'Nến thơm tạo không gian ấm áp và lãng mạn — một món quà tinh tế cho người yêu thích cảm giác thư giãn và aesthetic trong không gian sống.',
      estimatedPriceRange: '120.000đ - 250.000đ',
      searchKeyword: 'nến thơm hoa khô decor',
      emoji: '🕯️',
      category: 'Trang trí',
    },
    {
      id: '4',
      productName: 'Vòng tay đôi bạc khắc tên',
      reason: 'Vòng tay đôi là biểu tượng của sự kết nối. Khắc tên hoặc ngày kỷ niệm sẽ biến món quà thành kỷ vật quý giá không thể quên.',
      estimatedPriceRange: '280.000đ - 500.000đ',
      searchKeyword: 'vòng tay đôi bạc khắc tên',
      emoji: '💍',
      category: 'Trang sức',
    },
    {
      id: '5',
      productName: 'Album ảnh polaroid tự trang trí',
      reason: 'Lưu giữ những kỷ niệm hai người theo cách thủ công và chân thật nhất — album ảnh handmade cho thấy bạn đã dành thời gian và tâm huyết cho món quà này.',
      estimatedPriceRange: '100.000đ - 200.000đ',
      searchKeyword: 'album ảnh polaroid trang trí',
      emoji: '📷',
      category: 'Kỷ niệm',
    },
    {
      id: '6',
      productName: 'Nước hoa mini set 5 mùi',
      reason: 'Set nước hoa mini cho phép thử nhiều mùi hương khác nhau — một món quà sang trọng mà không cần tốn quá nhiều ngân sách, phù hợp với người yêu thích làm đẹp.',
      estimatedPriceRange: '180.000đ - 320.000đ',
      searchKeyword: 'nước hoa mini set',
      emoji: '🌸',
      category: 'Làm đẹp',
    },
  ],
  default: [
    {
      id: '1',
      productName: 'Bình giữ nhiệt Stanley 1L',
      reason: 'Thực tế và bền bỉ — bình giữ nhiệt chất lượng cao là người bạn đồng hành tốt nhất cho cuộc sống bận rộn hàng ngày của người nhận.',
      estimatedPriceRange: '350.000đ - 600.000đ',
      searchKeyword: 'bình giữ nhiệt stanley',
      emoji: '🥤',
      category: 'Đồ dùng',
    },
    {
      id: '2',
      productName: 'Voucher spa massage thư giãn',
      reason: 'Tặng một buổi thư giãn trọn vẹn là cách nói "mình quan tâm đến sức khỏe của bạn" — đặc biệt ý nghĩa với người hay stress và bận rộn.',
      estimatedPriceRange: '300.000đ - 500.000đ',
      searchKeyword: 'voucher spa massage',
      emoji: '💆',
      category: 'Trải nghiệm',
    },
    {
      id: '3',
      productName: 'Tai nghe không dây chống ồn',
      reason: 'Với người yêu âm nhạc hoặc làm việc cần tập trung, tai nghe chống ồn là món quà vừa thiết thực vừa nâng cấp chất lượng cuộc sống đáng kể.',
      estimatedPriceRange: '500.000đ - 900.000đ',
      searchKeyword: 'tai nghe không dây chống ồn',
      emoji: '🎧',
      category: 'Công nghệ',
    },
    {
      id: '4',
      productName: 'Set bút viết aesthetic Pilot',
      reason: 'Đơn giản nhưng luôn hữu ích — set bút chất lượng cao là món quà nhỏ nhưng khiến người nhận vui mỗi lần cầm lên viết.',
      estimatedPriceRange: '80.000đ - 150.000đ',
      searchKeyword: 'bút viết pilot aesthetic set',
      emoji: '✒️',
      category: 'Văn phòng phẩm',
    },
    {
      id: '5',
      productName: 'Túi da đựng đồ cá nhân',
      reason: 'Tinh tế và sang trọng, túi da mini là phụ kiện đa năng — đựng mỹ phẩm, sạc dự phòng, hoặc đơn giản là trang trí thêm cho chiếc túi xách.',
      estimatedPriceRange: '200.000đ - 400.000đ',
      searchKeyword: 'túi da đựng đồ cosmetic pouch',
      emoji: '👜',
      category: 'Thời trang',
    },
    {
      id: '6',
      productName: 'Máy xông tinh dầu mini USB',
      reason: 'Thư giãn tại nhà với hương thơm tinh dầu tự nhiên — nhỏ gọn, dễ dùng, và tạo không khí dễ chịu cho không gian làm việc hay phòng ngủ.',
      estimatedPriceRange: '120.000đ - 220.000đ',
      searchKeyword: 'máy xông tinh dầu mini usb',
      emoji: '🌿',
      category: 'Sức khỏe',
    },
  ],
};

// ============================================================
// MOCK PRODUCTS
// Realistic Vietnamese e-commerce products
// ============================================================

const MOCK_SHOPEE_PRODUCTS: Product[] = [
  {
    id: 'sp1',
    name: 'Bình giữ nhiệt khắc tên - Inox 304 500ml giữ nóng 12h',
    price: 185000,
    originalPrice: 250000,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
    rating: 4.9,
    reviewCount: 2847,
    sold: 15200,
    source: 'shopee',
    affiliateLink: 'https://shopee.vn/',
    discount: 26,
    badge: 'Bán chạy',
  },
  {
    id: 'sp2',
    name: 'Bình giữ nhiệt Stanley Quencher 1L - Chính hãng',
    price: 520000,
    originalPrice: 650000,
    imageUrl: 'https://images.unsplash.com/photo-1567922045116-2a00fae2ed03?w=400&h=400&fit=crop',
    rating: 4.8,
    reviewCount: 1203,
    sold: 8900,
    source: 'shopee',
    affiliateLink: 'https://shopee.vn/',
    discount: 20,
    badge: 'Chính hãng',
  },
  {
    id: 'sp3',
    name: 'Bình giữ nhiệt Hydro Flask 350ml màu pastel',
    price: 165000,
    originalPrice: 180000,
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=400&h=400&fit=crop',
    rating: 4.7,
    reviewCount: 892,
    sold: 5600,
    source: 'shopee',
    affiliateLink: 'https://shopee.vn/',
    discount: 8,
  },
  {
    id: 'sp4',
    name: 'Bình giữ nhiệt mini 350ml in hình cute',
    price: 89000,
    originalPrice: 120000,
    imageUrl: 'https://images.unsplash.com/photo-1553531087-b7b9b2e9d1b4?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 3421,
    sold: 22000,
    source: 'shopee',
    affiliateLink: 'https://shopee.vn/',
    discount: 26,
    badge: 'Giá tốt',
  },
  {
    id: 'sp5',
    name: 'Bình giữ nhiệt LOCKNLOCK 500ml có quai xách',
    price: 135000,
    originalPrice: 160000,
    imageUrl: 'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 678,
    sold: 4200,
    source: 'shopee',
    affiliateLink: 'https://shopee.vn/',
    discount: 16,
  },
  {
    id: 'sp6',
    name: 'Bình giữ nhiệt Remo Store - Khắc tên miễn phí',
    price: 198000,
    originalPrice: 230000,
    imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&h=400&fit=crop',
    rating: 4.8,
    reviewCount: 1567,
    sold: 9800,
    source: 'shopee',
    affiliateLink: 'https://shopee.vn/',
    discount: 14,
    badge: 'Khắc miễn phí',
  },
];

const MOCK_TIKTOK_PRODUCTS: Product[] = [
  {
    id: 'tt1',
    name: 'Bình giữ nhiệt viral TikTok - Gradient màu pastel 600ml',
    price: 145000,
    originalPrice: 200000,
    imageUrl: 'https://images.unsplash.com/photo-1610824352934-c10d87b700cc?w=400&h=400&fit=crop',
    rating: 4.7,
    reviewCount: 4521,
    sold: 31000,
    source: 'tiktok',
    affiliateLink: 'https://tiktok.com/',
    discount: 28,
    badge: 'Viral TikTok',
  },
  {
    id: 'tt2',
    name: 'Bình giữ nhiệt aesthetic y2k - Sticker included',
    price: 119000,
    originalPrice: 150000,
    imageUrl: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 2890,
    sold: 18500,
    source: 'tiktok',
    affiliateLink: 'https://tiktok.com/',
    discount: 21,
  },
  {
    id: 'tt3',
    name: 'Bình nước thermos mini - Trend 2024 Gen Z',
    price: 78000,
    originalPrice: 99000,
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 5678,
    sold: 45000,
    source: 'tiktok',
    affiliateLink: 'https://tiktok.com/',
    discount: 21,
    badge: 'Giá sốc',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  ...MOCK_SHOPEE_PRODUCTS,
  ...MOCK_TIKTOK_PRODUCTS,
].sort((a, b) => a.price - b.price);

// ============================================================
// MOCK STORES
// Realistic Vietnamese store locations (Hanoi area)
// ============================================================

export const MOCK_STORES: Store[] = [
  {
    id: 'st1',
    name: 'The Gift Shop - Quà tặng cao cấp',
    address: '52 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    distanceMeters: 320,
    rating: 4.8,
    reviewCount: 342,
    openNow: true,
    hours: '08:00 - 22:00',
    lat: 10.7769,
    lng: 106.7009,
    phone: '028 3821 4567',
    category: 'Quà tặng',
    features: ['Quà tặng cao cấp', 'Gói quà miễn phí', 'Cá nhân hóa'],
  },
  {
    id: 'st2',
    name: 'GiftBox VN - Quà tặng cá nhân hóa',
    address: '138 Lê Thánh Tôn, Phường Bến Thành, Quận 1, TP.HCM',
    distanceMeters: 780,
    rating: 4.6,
    reviewCount: 218,
    openNow: true,
    hours: '09:00 - 21:30',
    lat: 10.7752,
    lng: 106.6985,
    phone: '028 3914 2233',
    category: 'Quà tặng cá nhân hóa',
    features: ['In tên miễn phí', 'Hộp quà đẹp', 'Ship tận nơi'],
  },
  {
    id: 'st3',
    name: 'Miniso Vincom Center',
    address: 'Tầng 2, Vincom Center, 72 Lê Thánh Tôn, Quận 1, TP.HCM',
    distanceMeters: 1200,
    rating: 4.5,
    reviewCount: 891,
    openNow: true,
    hours: '09:30 - 22:00',
    lat: 10.7798,
    lng: 106.7012,
    phone: '028 3636 9988',
    category: 'Chuỗi bán lẻ Nhật Bản',
    features: ['Đồ gia dụng', 'Mỹ phẩm', 'Phụ kiện thời trang'],
  },
  {
    id: 'st4',
    name: 'Quà Tặng Ý Nghĩa',
    address: '75 Võ Thị Sáu, Phường 6, Quận 3, TP.HCM',
    distanceMeters: 2100,
    rating: 4.7,
    reviewCount: 156,
    openNow: false,
    hours: '08:30 - 20:00',
    lat: 10.7863,
    lng: 106.6867,
    phone: '028 3845 7788',
    category: 'Quà tặng',
    features: ['Gói quà handmade', 'Thiệp cá nhân hóa'],
  },
  {
    id: 'st5',
    name: 'Artbox Gift & Lifestyle',
    address: 'Tầng 3, Takashimaya, 65 Lê Lợi, Quận 1, TP.HCM',
    distanceMeters: 2800,
    rating: 4.9,
    reviewCount: 523,
    openNow: true,
    hours: '10:00 - 21:30',
    lat: 10.7731,
    lng: 106.6978,
    phone: '028 3910 0101',
    category: 'Lifestyle & Quà tặng',
    features: ['Phong cách Hàn', 'Decor phòng', 'Trang sức nhỏ'],
  },
];
